models/Order.php
<?php

namespace app\models;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property string $date_add
 * @property string $status
 * @property double $sum
 * @property double $weight
 * @property string $receiver_date
 * @property int $receiver_city
 * @property string $receiver_address
 * @property string $receiver_name
 * @property string $receiver_phone
 * @property string $receiver_email
 * @property int $sender_city
 * @property string $sender_address
 * @property string $comment
 *
 * @property City $receiverCity
 * @property City $senderCity
 */
class Order extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'order';
    }

    /* Возвращает список заявок "пригодных" для рейса */
	public static function getOrdersForShipping($shipping) {

        // 1. Нам необходимы "свободные" заявки, т.е. еще не в рейсах.
        $orders = Order::find()->join('LEFT JOIN', 'shipping_detail', 'order.id = order_id')
            ->where('order_id IS NULL')->orderBy('order.id')->all();

        // 2. Город отправления и Город получения по заявке должен соответствовать маршруту рейса.
        $cities = $shipping->route->citiesObj;
        $ordersForShipping = [];
        foreach ($orders as $order) {
            $key_start = array_search($order->senderCity, $cities);
            $key_finish = array_search($order->receiverCity, $cities);

            if ($key_start === false || $key_finish === false || $key_finish <= $key_start) {
                continue;
            }
            $ordersForShipping[] = $order;
        }

		return $ordersForShipping;
    }	

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
                [['sender_city', 'sender_address', 'receiver_city', 'receiver_address', 'receiver_date', 'weight'], 'required'],
                [['date_add', 'unload_type', 'payment_method', 'sender_time_from', 'sender_time_to', 'receiver_time_from', 'receiver_time_to'], 'safe'],
                [['sum', 'weight', 'cargo_volume'], 'number'],
                [['receiver_city', 'sender_city', 'driver_id'], 'integer'],
                [['status', 'cargo_quantity_seats', 'receiver_address', 'receiver_name', 'receiver_phone', 'receiver_email', 'sender_address', 'comment', 'client', 'performer'], 'string', 'max' => 255],
                [['receiver_city'], 'exist', 'skipOnError' => true, 'targetClass' => City::className(), 'targetAttribute' => ['receiver_city' => 'id']],
                [['sender_city'], 'exist', 'skipOnError' => true, 'targetClass' => City::className(), 'targetAttribute' => ['sender_city' => 'id']],
                [['sender_date', 'receiver_date'], 'filter', 'filter' => function($value) {
                    if ($value == '')
                        return NULL;
                    return date('Y-m-d', strtotime($value));
                }],
                [['cargo_name', 'payment_condition', 'sender', 'sender_name', 'sender_phone', 'receiver', 'driver', 'driver_phone', 'driver_passport', 'truck_number'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'Номер',
            'date_add' => 'Дата создания',
            'dateAddFormat' => 'Дата создания',
            'status' => 'Статус',
            'statusName' => 'Статус',
            'sum' => 'Сумма',
            'weight' => 'Вес, т',
            'receiver_date' => 'Дата получения',
            'receiverDateFormat' => 'Дата получения',
            'receiver_city' => 'Город получения',
            'receiver_address' => 'Адрес получения',
            'receiver_name' => 'Имя представителя',
            'receiver_phone' => 'Телефон',
            'receiver_email' => 'Email',
            'sender_city' => 'Город отправления',
            'sender_address' => 'Адрес отправления',
            'senderCityName' => 'Город отправления',
            'receiverCityName' => 'Город получения',
            'comment' => 'Комментарий',
            'unload_type' => 'Вид загрузки/выгрузки',
            'unloadTypeName' => 'Вид загрузки/выгрузки',
            'cargo_name' => 'Наименование груза',
            'cargo_volume' => 'Объём груза, м3',
            'cargo_quantity_seats' => 'Кол-во мест, палет',
            'payment_method' => 'Способ оплаты',
            'paymentMethodName' => 'Способ оплаты',
            'payment_condition' => 'Условия оплаты',
            'sender' => 'Грузоотправитель',
            'sender_name' => 'Имя представителя',
            'sender_phone' => 'Телефон',
            'receiver' => 'Грузополучатель',
            'driverName' => 'Водитель',
            'driver_phone' => 'Телефон водителя',
            'driver_passport' => 'Паспорт/Водительское удостоверение',
            'truck_number' => 'Марка и гос. номер транспортного средства',
            'client' => 'Заказчик',
            'performer' => 'Исполнитель',
            'sender_date' => 'Дата отправления',
            'senderDateFormat' => 'Дата отправления',
            'sender_time_from' => 'Время отправления с',
            'sender_time_to' => 'Время отправления по',
            'receiver_time_from' => 'Время получения с',
            'receiver_time_to' => 'Время получения по',
            'driver_id' => 'Водитель',
        ];
    }

    public function getStatuses() {

        return [
            '1' => 'Новая',
            '2' => 'В работе',
            '3' => 'Выполнено',
        ];
    }

    public function getStatusName() {

        return $this->statuses[$this->status];
    }

    public function getUnloadTypes() {

        return [
            'tent' => 'Тент',
            'zadnaya' => 'Задняя',
        ];
    }

    public function getUnloadTypeName() {

        return $this->unloadTypes[$this->unload_type];
    }

    public function getPaymentMethods() {

        return [
            'cash' => 'Нал',
            'noncash' => 'Безнал',
            'noncashWithNDS' => 'Безнал с НДС',
        ];
    }

    public function getPaymentMethodName() {

        return $this->paymentMethods[$this->payment_method];
    }

    public function getDateAddFormat() {

       if ($this->date_add) {
			return date('d.m.Y H:i:s', strtotime($this->date_add));
		} else return '';
    }

    public function getReceiverDateFormat() {

        return date('d.m.Y', strtotime($this->receiver_date));
    }

    public function getSenderDateFormat() {

        return date('d.m.Y', strtotime($this->sender_date));
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getReceiverCity() {
        return $this->hasOne(City::className(), ['id' => 'receiver_city']);
    }

    public function getReceiverCityName() {
        if (isset($this->receiverCity))
            return $this->receiverCity->name;
        else
            return '';
    }

    public function getDriverInst() {
        return $this->hasOne(Driver::className(), ['id' => 'driver_id']);
    }

    public function getDriverName() {
        if (isset($this->driverInst))
            return $this->driverInst->name;
        else
            return '';
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSenderCity() {
        return $this->hasOne(City::className(), ['id' => 'sender_city']);
    }

    public function getSenderCityName() {
        if (isset($this->senderCity))
            return $this->senderCity->name;
        else
            return '';
    }

    public function beforeSave($insert) {

        if (!parent::beforeSave($insert)) {
            return false;
        }

        if ($insert) {
            $this->date_add = date('Y-m-d H:i:s');
        }

        return true;
    }

}

controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Driver;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['index', 'view'],
                        'roles' => ['logistician'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['dispatcher'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionSearchDriver($q = null)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $drivers = Driver::find()
            ->orFilterWhere(['like', 'name', $q])
            ->orFilterWhere(['like', 'phone', $q])
            ->orFilterWhere(['like', 'truck_number', $q])
            ->orderBy('name')
            ->limit(10)
            ->all();

        $out['items'] = [];
        $out["total_count"] = 10;
        $out["incomplete_results"] = false;
        foreach ($drivers as $i => $driver) {
            $out['items'][$i] = [
                'id' => $driver['id'],
                'name' => $driver['name'],
                'phone' => $driver['phone'],
                'passport' => $driver['passport'],
                'truck_number' => $driver['truck_number'],
            ];
        }

        return $out;
    }

    public function actionGetDriverInfo($id = null)
    {
        if ($id) {
            $model = Driver::findOne($id);
        }
        return $this->renderPartial('_driver_info', [
            'model' => $model ? $model : null,
        ]);
    }
    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/order/_driver_info.php
<?php

$script = <<< JS
    $(document).ready(function(){
        $(document).on("change", "#driver_id", function(e){
            var _this = $(this);
            $.ajax({
                type: "GET",
                url: "/order/get-driver-info",
                data:{id:_this.val()},
                success: function(msg){
                    $("#driver_info").html($(msg));
                },               
            });
        });
    });
JS;
$this->registerJs($script, yii\web\View::POS_READY);

?>

<div id="driver_info">
    <?php if ($model): ?>

        <?= $model->phone ?> <br>
        <?= $model->passport ?> <br>
        <?= $model->truck_number ?> <br><br>

    <?php endif ?>

</div>

views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\JsExpression;
use kartik\select2\Select2;
use app\models\City;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $model app\models\Order */
/* @var $form yii\widgets\ActiveForm */

$formatJs = <<< 'JS'

var formatRepo = function (repo) {
    if (repo.loading) {
        return repo.text;
    }
    var markup =
'<div class="row">' + 
    '<div class="col-sm-12">' +
        '<div><b style="margin-left:5px">' + repo.name + '</b></div>' + 
        '<div><b style="margin-left:5px">' + repo.phone + '</b></div>' + 
        '<div><b style="margin-left:5px">' + repo.passport + '</b></div>' + 
        '<div><b style="margin-left:5px">' + repo.truck_number + '</b></div>' + 
    '</div>' +
'</div>';   
    return '<div style="overflow:hidden;">' + markup + '</div>';
};
var formatRepoSelection = function (repo) {
    return repo.name || repo.text;
}
JS;

// Register the formatting script
$this->registerJs($formatJs, View::POS_HEAD);

// script to parse the results into the format expected by Select2
$resultsJs = <<< JS
function (data, params) {
    params.page = params.page || 1;
    return {
        results: data.items,
        pagination: {
            more: (params.page * 30) < data.total_count
        }
    };
}
JS;

?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="panel panel-default panel-body">

        <?php $cities = City::find()->orderBy('name')->all(); ?>

        <div class="row">
            <div class="col-md-3">
                <?=
                $form->field($model, 'sender_city')->widget(Select2::classname(), [
                    'data' => ArrayHelper::Map($cities, 'id', 'name'),
                    'options' => ['placeholder' => 'Выберите город...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>		
            </div>
            <div class="col-md-9">
                <?= $form->field($model, 'sender_address')->textInput(['maxlength' => true, 'placeholder' => 'ул. Каштановая, 17']) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <?= $form->field($model, 'sender')->textInput(['maxlength' => true, 'placeholder' => 'ООО "ВИД"']) ?>
            </div>
            <div class="col-md-7">
                <?= $form->field($model, 'sender_name')->textInput(['maxlength' => true, 'placeholder' => 'Игорь Васильевич, логист']) ?>
            </div>

            <div class="col-md-2">
                <?= $form->field($model, 'sender_phone')->textInput(['maxlength' => true]) ?>

            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <?=
                $form->field($model, 'sender_date')->widget(\yii\jui\DatePicker::classname(), [
                    'language' => 'ru',
                    'dateFormat' => 'dd.MM.yyyy',
                    'options' => ['class' => 'form-control'],
                ])
                ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'sender_time_from')->widget(\kartik\time\TimePicker::classname(), [
                    'pluginOptions' => [
                        'showMeridian' => false,
                        'format' => "hh:mm",
                        'defaultTime' => false,
                        'minuteStep' => 5,
                    ],
                ]); ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'sender_time_to')->widget(\kartik\time\TimePicker::classname(), [
                    'pluginOptions' => [
                        'showMeridian' => false,
                        'format' => "hh:mm",
                        'defaultTime' => false,
                        'minuteStep' => 5,
                    ],
                ]); ?>
            </div>
        </div>
    </div>
    <div class="panel panel-default panel-body">

        <div class="row">
            <div class="col-md-3"> 	
                <?=
                $form->field($model, 'receiver_city')->widget(Select2::classname(), [
                    'data' => ArrayHelper::Map($cities, 'id', 'name'),
                    'options' => ['placeholder' => 'Выберите город...'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]);
                ?>				
            </div>
            <div class="col-md-9">
                <?= $form->field($model, 'receiver_address')->textInput(['maxlength' => true, 'placeholder' => 'ул. Ленина, 34 "Б"']) ?>
            </div>          

        </div>

        <div class="row">

            <div class="col-md-3">
                <?= $form->field($model, 'receiver')->textInput(['maxlength' => true, 'placeholder' => 'ООО "Синие тучи"']) ?>
            </div>

            <div class="col-md-7">
                <?= $form->field($model, 'receiver_name')->textInput(['maxlength' => true, 'placeholder' => 'Ренат Носов, менеджер']) ?>
            </div>

            <div class="col-md-2">
                <?= $form->field($model, 'receiver_phone')->textInput(['maxlength' => true]) ?>
            </div>

        </div>

        <div class="row">
            <div class="col-md-3">
                <?=
                $form->field($model, 'receiver_date')->widget(\yii\jui\DatePicker::classname(), [
                    'language' => 'ru',
                    'dateFormat' => 'dd.MM.yyyy',
                    'options' => ['class' => 'form-control'],
                ])
                ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'receiver_time_from')->widget(\kartik\time\TimePicker::classname(), [
                    'pluginOptions' => [
                        'showMeridian' => false,
                        'format' => "hh:mm",
                        'defaultTime' => false,
                        'minuteStep' => 5,
                    ],
                ]); ?>
            </div>
            <div class="col-md-3">
                <?= $form->field($model, 'receiver_time_to')->widget(\kartik\time\TimePicker::classname(), [
                    'pluginOptions' => [
                        'showMeridian' => false,
                        'format' => "hh:mm",
                        'defaultTime' => false,
                        'minuteStep' => 5,
                    ],
                ]); ?>
            </div>
        </div>
    </div>

    <div class="panel panel-default panel-body">

        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'client')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'performer')->textInput(['maxlength' => true]) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <?= $form->field($model, 'unload_type')->dropDownList($model->unloadTypes, ['prompt' => 'Выберите значение...']); ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'cargo_name')->textInput(['maxlength' => true, 'placeholder' => 'Пищевые добавки']) ?>
            </div>
            <div class="col-md-1">
                <?= $form->field($model, 'weight')->textInput() ?>
            </div>
            <div class="col-md-2">
                <?= $form->field($model, 'cargo_volume')->textInput() ?>
            </div>
            <div class="col-md-2">
                <?= $form->field($model, 'cargo_quantity_seats')->textInput() ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <?= $form->field($model, 'sum')->textInput() ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'payment_method')->dropDownList($model->paymentMethods, ['prompt' => 'Выберите значение...']); ?>
            </div>
            <div class="col-md-5">
                <?= $form->field($model, 'payment_condition')->textInput(['maxlength' => true, 'placeholder' => 'После доставки груза']) ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?= $form->field($model, 'driver_id')->widget(Select2::classname(), [
                    'name' => 'kv-repo-template',
                    'value' => '14719648',
                    'initValueText' => $model->driverName,
                    'options' => [
                        'placeholder' => 'Поиск по полям "Имя", "Телефон", "Марка и гос.№ трансп. средства"',
                        'id' => 'driver_id',
                    ],
                    'pluginOptions' => [
                        'allowClear' => true,
                        'minimumInputLength' => 1,
                        'ajax' => [
                            'url' => Url::to(['order/search-driver']),
                            'dataType' => 'json',
                            'delay' => 250,
                            'data' => new JsExpression('function(params) { return {q:params.term, page: params.page}; }'),
                            'processResults' => new JsExpression($resultsJs),
                            'cache' => true
                        ],
                        'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                        'templateResult' => new JsExpression('formatRepo'),
                        'templateSelection' => new JsExpression('formatRepoSelection'),
                    ],
                ]); ?>

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <?= $this->render('_driver_info', [
                    'model' => $model->driverInst,
                ]); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <?= $form->field($model, 'comment')->textInput(['maxlength' => true]) ?>
            </div>

            <div class="col-md-2">
                <?= $form->field($model, 'status')->dropDownList($model->statuses); ?>	 
            </div>

            <div class="col-md-2">
                <?= $form->field($model, 'dateAddFormat')->textInput(['disabled' => true]) ?>
            </div>
        </div>    
    </div>

    <div class="form-group">
        <?= Html::submitButton('Записать', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'date_add') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'sum') ?>

    <?= $form->field($model, 'weight') ?>

    <?php // echo $form->field($model, 'receiver_date') ?>

    <?php // echo $form->field($model, 'receiver_city') ?>

    <?php // echo $form->field($model, 'receiver_address') ?>

    <?php // echo $form->field($model, 'receiver_name') ?>

    <?php // echo $form->field($model, 'receiver_phone') ?>

    <?php // echo $form->field($model, 'receiver_email') ?>

    <?php // echo $form->field($model, 'sender_city') ?>

    <?php // echo $form->field($model, 'sender_address') ?>

    <?php // echo $form->field($model, 'comment') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Создание новой заявки';
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Заявки';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="panel panel-default panel-body">	

        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                'id',
                    [
                    'attribute' => 'date_add',
                    'content' => function($data) {
                        return $data->dateAddFormat;
                    }
                ],
                    [
                    'attribute' => 'status',
                    'content' => function($data) {
                        return $data->statusName;
                    }
                ],
                    [
                    'attribute' => 'sender_city',
                    'content' => function($data) {
                        return $data->senderCityName;
                    }
                    ],
                [
                    'attribute' => 'receiver_city',
                    'content' => function ($data) {
                        return $data->receiverCityName;
                    }
                ],
                [
                    'attribute' => 'receiver_date',
                    'content' => function ($data) {
                        return $data->receiverDateFormat;
                    }
                ],
                'weight',
                'sum',
                //'receiver_date',
                //'receiver_city',
                //'receiver_address',
                //'receiver_name',
                //'receiver_phone',
                //'receiver_email:email',
                //'sender_city',
                //'sender_address',
                //'comment',
                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]);
        ?>

    </div>
</div>

views/order/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Заявка №' . $model->id . ' от ' . $model->dateAddFormat;
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Заявка №' . $model->id . ' от ' . $model->dateAddFormat, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="order-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/order/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Order */

$this->title = 'Заявка №' . $model->id . ' от ' . $model->dateAddFormat;
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Изменить', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?=
        Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить этот элемент?',
                'method' => 'post',
            ],
        ])
        ?>
    </p>

    <?=
    DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'dateAddFormat',
            'senderCityName',
            'sender_address',
            'sender',
            'sender_name',
            'sender_phone',
            'senderDateFormat',
            'sender_time_from',
            'sender_time_to',
            'receiverCityName',
            'receiver_address',
			'receiver',
            'receiver_name',
            'receiver_phone',
            'receiver_email',
            'receiverDateFormat',
            'receiver_time_from',
            'receiver_time_to',
            'client',
            'performer',
            'unloadTypeName',
            'cargo_name',
            'weight',
            'cargo_volume',
            'cargo_quantity_seats',
            'sum',
            'paymentMethodName',
            'payment_condition',
            'driverName',
            'comment',
            'statusName',
        ],
    ])
    ?>

</div>